name: 'GitHub Actions Flyingaway Crawler'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 00 * * *'

jobs:
  gif-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r ./requirements.txt
      - name: Checkout file fingers
        uses: moonrailgun/branch-filestorage-action@v1.2.0
        with:
          path: data/fingers.json
      - name: 'Working'
        run: python ./run_time.py

# name: Tests

# on:
#   push:
#     branches: 
#       - master
#   # workflow_dispatch:

# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Checkout file date
#       uses: moonrailgun/branch-filestorage-action@v1.2.0
#       with:
#         path: date testdir
#     - name: Read and show
#       run: touch date && cat date
#     - name: update date
#       run: echo $(date) > date
#     - name: update date
#       run: echo 123 > dat


